name: flutter_wallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  provide: ^1.0.2
  flutter_screenutil: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/home.png
   - assets/home_active.png
   - assets/member.png
   - assets/member_active.png
   - assets/propagate.png
   - assets/propagate_active.png
   - assets/share.png
   - assets/share_active.png
   - assets/module_bg_blue.png
   - assets/module_bg_red.png
   - assets/module_bg_yellow.png
   - assets/module_bg_green.png
   - assets/icon_mer_join.png
   - assets/icon_mer_money.png
   - assets/icon_qr_code.png
   - assets/icon_query_bill.png
   - assets/icon_loan.png
   - assets/icon_card.png
   - assets/icon_inte.png
   - assets/icon_cheng_hui.png
   - assets/cheng_bg_1.png
   - assets/share_bg.png
   - assets/icon_tooltip.png
   - assets/icon_user.png
   - assets/member_bg_total.png
   - assets/icon_money.png
   - assets/icon_bank_card.png
   - assets/icon_add_user.png
   - assets/icon_feedback.png
   - assets/icon_settings.png



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
